version: '3.5'

services:
  app:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - internal
  
  webserver:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./public:/usr/share/nginx/html
    networks:
      - internal

  db:
    container_name: symfony_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "dbCalendario"
      MYSQL_USER: "usuario"
      MYSQL_PASSWORD: "usuario"
    ports:
      - 3306:3306
    volumes:
      - symfony-data:/var/lib/mysql
    networks:
      - internal

volumes:
  symfony-data:

networks:
  internal:
    driver: bridge